travis:
  secure:
    BINSTAR_TOKEN: WlcVt3/HuqvjuCZr8NqGRTXK/DCx3cplzmnkd9CzTbEN2uC3ZAqZlUBo/2rCV3MjwmsGmDjzfBiFxwp/cKABPOWw8dWdpNmS8nI5Y6dB7ekdNXFEAz6+IimVR3G+UTyuUI48r4QyksAvkyU7LXSFRnVkfSDtgEeAetyDaWfdWpFjiyj5yH1Vel+vlNaL5KYeWbtieglC3poaMCVlvbNMcq5eJea2mjhR1n0mWlLTe3RLp7Ty5iWJIgq5u9IypBhamhCyLUhtiSoBWL6dE1WKdXVs9XvcJbkITIZ/D6QXbj25hq7MnHjqLpSamtpyuNXe9iaBbK8reeiabu0KiF0siR7TopwpMRhTUZCQo9CsT5OelNCQHwgz1VjIZFu5+ms4+wGR+NCgC2MTPEhJ1y0XJJs6fZXIePcOZCo2DRg0LOouo/f07X5VaoVoiOn35jA0aYyysrAyrviLtGAeY+sTaDMoRE4BBjcisGGOpgCRxtDwAN4+BViOeozSKFMcfUmIasQ3Ljq/XYWPpYqOhakCJHnj/715Ol0e8gertUU1dkDvdgDfluRBqIZWY4j8r9aRPCcM1yF0ofSdy5xp2gbaE060DCvHJ4azs4DhGSAlPh7yvhtEGavc5argdMhjATbQ2MU+4whirChi7PVGfGI42jy00XdzdzxUxgsRzrStDOY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
